### ISSUE TITLE
nmon logger can't get all disk partitions in my system. 

### ISSUE THREAD

**Issue by zbw1983** [guilhemmarchand/nmon-for-splunk#96] opened 2017-08-25 06:59 UTC
Hi 
I use nmon-logger-rsyslog-2.0.4-0.noarch on my server, but I found on some of servers, it can't get all hard disk partition information. 

Here is my partition/mount folder list: 

/dev/sda3       127G   14G  107G  12% /
devtmpfs        126G     0  126G   0% /dev
tmpfs           126G   12K  126G   1% /dev/shm
tmpfs           126G  4.1G  122G   4% /run
tmpfs           126G     0  126G   0% /sys/fs/cgroup
/dev/sda1       239M  110M  112M  50% /boot
tmpfs            26G     0   26G   0% /run/user/800
/dev/sdb1       6.5T  3.3T  3.3T  50% /export
/dev/sdc1       6.5T  3.1T  3.5T  48% /export1
/dev/sdd1       6.5T  4.4T  2.2T  68% /export2
tmpfs            26G     0   26G   0% /run/user/999900
tmpfs            26G     0   26G   0% /run/user/598

But in NMON, I can't get /export2 partition information. 

In original data file nmon_config.dat, I can find export2 information like below: 

nmon_config.dat:BBBP,033,lsblk,"└─sdd1 8:49 0 6.6T 0 part /export2"
nmon_config.dat:BBBP,1164,/bin/df-m,"ddev/sdd1 6813380 4669481 2143883 69% /export2"
nmon_config.dat:BBBP,1201,/bin/mount,"ddev/sdd1 on /export2 type ext4 (rw,noatime,stripe=384,data=ordered)"
nmon_config.dat:BBBP,1218,/etc/fstab,"LABEL=/export2 /export2 ext4 defaults,noatime 0 0"

But in final log file nmon_perfdata.log,  there is no /export2 information, while /export and /export1 are there. 

Could you help to check what's wrong?

**Comment by guilhemmarchand** [comment] 2017-08-25 08:50
Hello !

Right, this looks strange indeed.

**Could double check the following based on your server example:**

replace "sdd*" if relevant: (this is for disks perf metrics)

```
eventtype=nmon:performance:storage type=DISK* OR type=DG* device=sdd*
|  stats count by host,type,device

```
**And this is for file system pct utilisation:**

```
eventtype=nmon:performance:storage type=JFSFILE device=*export2*
|  stats count by host,type,device
```

To be sure that you don't have the file system and disk being reported by Nmon.

The collection (a new binary occurrence) starts every 24 hours, ensure that the file system you are looking for has not been added and mounted too recently to be captured by nmon.

**You can finally run manually an nmon process on one of the servers and verify if this file system / disk is being reported, identify the binary currently used by the nmon-logger, replace the "-F xxxxx" by "-f", example:**

```
ps -ef | grep nmon
nmon      3544     1  0 09:47 ?        00:00:00 python /etc/nmon-logger/bin/fifo_reader.py --fifo fifo1
nmon      3546  3544  0 09:47 ?        00:00:00 /bin/sh -c /etc/nmon-logger/bin/fifo_reader.sh /var/log/nmon-logger/var/nmon_repository/fifo1/nmon.fifo
nmon      3547  3546  0 09:47 ?        00:00:00 /bin/sh /etc/nmon-logger/bin/fifo_reader.sh /var/log/nmon-logger/var/nmon_repository/fifo1/nmon.fifo
nmon      3569     1  0 09:47 ?        00:00:00 /var/log/nmon-logger/bin/linux/ubuntu/nmon_x86_64_ubuntu1604 -F /var/log/nmon-logger/var/nmon_repository/fifo1/nmon.fifo -T -s 60 -c 1440 -d 1500 -g auto -D -p
guilhem   4294  2983  0 09:48 pts/2    00:00:00 grep --color=auto nmon

~$ /var/log/nmon-logger/bin/linux/ubuntu/nmon_x86_64_ubuntu1604 -f -T -s 60 -c 1440 -d 1500 -g auto -D -p
Generating disk group file from lsblk output to file: "auto"
4484
~$ grep JFSFILE GMD-LAPTOP_170825_0949.nmon 
JFSFILE,JFS Filespace %Used GMD-LAPTOP,/dev,/run,/,/boot,/var/lib/lxcfs
JFSFILE,T0001,0.0,3.9,82.3,49.3,0.0
~$ grep DISKBUSY GMD-LAPTOP_170825_0949.nmon 
DISKBUSY,Disk %Busy GMD-LAPTOP,nvme0n1,nvme0n1p1,nvme0n1p2,nvme0n1p3,dm-0,dm-1,dm-2
DISKBUSY,T0001,0.0,0.0,0.0,0.0,0.0,0.0,0.0
 
```

Guilhem

**Comment by zbw1983** [comment] 2017-08-27 12:47
Thanks for your respond. 

`eventtype=nmon:performance:storage type=DISK* OR type=DG* device=sdd*
|  stats count by host,type,device`

Above search, I can get output. 

`eventtype=nmon:performance:storage type=JFSFILE device=*export2*
|  stats count by host,type,device`

Above search, I can't get any output. 

The SDD disk is on the machine for long time, so it should be captured by NMON. 

I run nmon command manually, and do grep as you did, below is the search result. 
`!891 # grep JFSFILE nycgmq01_170827_1237.nmon
JFSFILE,JFS Filespace %Used nycgmq01,/,/dev,/run,/,/boot,/export,/export1,/export2
JFSFILE,T0001,11.6,0.0,3.2,11.6,46.2,44.8,42.3,65.3`

Seems nmon get sdd1 information,  in SPLUNK nmon page, Linux -> NMON LIGHT ANALYSIS, I can't sdd1 information under "file system percent utilization"

**Comment by guilhemmarchand** [comment] 2017-08-28 08:44
Hi,

Thank for your reply,
The good new is that I am able to reproduce the issue, I will work on a fix and will let you know as soon as it is available,

Guilhem

**Comment by guilhemmarchand** [comment] 2017-09-01 15:26
Hello,

FYI, I am currently working on this issue, we will have a new collection (nmon external) that is currently available in testing branches.

The new collection called "DF_STORAGE" will replace the nmon internal collection "JFSFILE" specially because the JFSFILE is limited to the percentage of usage of the file systems.
The DF_STORAGE is basically the output of the df command and will contain all of its information. (which has been requested by some users, specially the volume for capacity planning purposes)

The original issue with JFSFILE remains unsure for me, sometimes it is captured, sometimes not, so not really sure if this is a bug of the nmon binary for Linux.

Anyway, the JFSFILE collection will be replaced by the DF_STORE (the JFSFILE will remain ingested though unless you deactivate it) which will solve your issue.

The Nmon core application is being currently updated and it shouldn't take long before both frontend and backend will be ready.

Regards,

Guilhem

**Comment by zbw1983** [comment] 2017-09-05 06:24
That’s is great, many thanks for your support. I think after stable version released, I can update nmon on my servers. And do I need update NMON UI application in splunk at same time? 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-09-05 10:17
Hi,

You are welcome.
The new releases should be ready within the end of the week.
And yes you will need to update the core application in Splunk to get benefit of these new monitors. (this not required for the ingestion thought)

Guilhem

**Comment by zbw1983** [comment] 2017-09-21 05:57
Hi Guilhem:

How about this issue? Is there any new version that fix it? Many thanks. 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-09-21 11:42
Hello Bowen,

Sorry for the delays, the nmon-logger package is ready and has been qualified and validated on all platforms, it is available in the master branch and the version is 2.0.9:

https://github.com/guilhemmarchand/nmon-logger

This release removes the "JFSFILE" section and indexes the "DF_STORAGE" and "DF_INODES" in replacement.

**To access the raw events, you will use the following searches in Splunk:**

`eventtype=nmon:performance type=DF_STORAGE OR type=DF_INODES`

Notes:
- The DF_STORAGE and DF_INODES section will be available after nmon-logger upgrade only when a new nmon process will be spawned, unless you kill the existing process. (so in 24 hours maximum after upgrade the data will start to be available)

Regarding the Nmon core application, it is not yet ready as I am ending some new features, please allow it a few days more to be full ready.

Guilhem

**Comment by guilhemmarchand** [comment] 2017-09-24 22:25
Hello Bowen,

The new release of the core application has been submitted for Splunk certification, and will be available on Splunk base as soon as it would be certified.

In the meanwhile, you can download the release directly from Github.

All other components, TA-nmon, nmon-logger, etc, are all update to date in their master branches.

Fell free to inform me if you have any issue with the new releases.

Regards,

Guilhem

**Comment by zbw1983** [comment] 2017-09-25 07:10
Hi Guilhem:

Thanks a lot, I will try to upgrade our NMON components recently. 

And for those new version packages, are they compatible with older version nmon-logger?  You know I have install nmon-logger 2.0.4 version on hundred of servers, I wonder whether I need upgrade all of them. The issue only happened on very few servers, so if new nmon core application can compatible with 2.0.4 version, I plan only update servers with that problem. 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-09-25 09:52
Hi Bowen,

Yes, the core application in version 1.9.11 will be able to manage the older nmon-logger data without any issue.

For the main dashboards like the summary overview and the Nmon analyser, there is a detection of DF_STORAGE versus JFSFILE availability.
I have a created a new dedicated STORAGE interface which will manage only the new DF_STORAGE collection. 
The Nmon dark dashboard will as well only use the new collection.

I'll double check this for the next core app release, but in any case this would be minor cases where it would be an issue.

Guilhem

**Comment by zbw1983** [comment] 2017-09-26 06:19
Hi Guihem:

I just update nmon-logger on one server to 2.0.9 version, and also update core application to 1911. After that, I still can't see export2 information on "nmon light analysis" page. 

I can get result by "eventtype=nmon:performance type=DF_STORAGE OR type=DF_INODES". 

But seems the dashboard use below search command which doesn't include export2 partition. Do I need any other operation to make it work? 

`| tstats max("JFS.value") AS JFS.value from datamodel=NMON_Data_JFS
where (nodename = JFS.JFSFILE) (JFS.value>=0) (host=nycgmq01.fwmrm.net) groupby _time, host, "JFS.device" prestats=true
| stats dedup_splitvals=t max("JFS.value") AS JFS.value by _time, "JFS.device"
| rename "JFS.device" AS device, "JFS.value" AS value
| stats max(value) AS max_value, avg(value) AS avg_value, min(value) AS min_value, latest(value) AS UsedPct by "device"
| sort limit=0 device | rename device AS "Mount point"
| eval value=round(value,2)
| fields "Mount point",max_value, avg_value, min_value, UsedPct | eval avg_value=round(avg_value,2)
| rename max_value AS "Max value in period (%)", avg_value AS "Average value in period (%)", min_value AS "Min value in Period (%)"`

**Comment by guilhemmarchand** [comment] 2017-09-26 06:41
Hi,

In the Summary overview dashboard, there is an hidden search that should detect the availability of the DF_STORAGE data and switch to it.

Have you checked the STORAGE dedicated interface ? (In the list of dedicated interfaces from the home page)
Could you verify that you don't have a local copy of the summary dashboard that would overwrite the default from the new release ?

**Comment by zbw1983** [comment] 2017-09-26 07:09
I open "Linux->DISKS/FILESYSTES -> JFSFILE >> File System Percentage Usage", I can't find /export2 information. 
In "Linux->GLOBAL ANALYSYS ->NMON LIGHT ANALYSIS", I also can't find /export2 information. 

I don't have any local copy, I am not sure whether I need restart SPLUNK after I update nmon core application. I haven't restarted splunk now. 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-09-26 07:31
Hi,

If the search head is standalone, Splunk must be restarted yes.
If you have a sh cluster, this would be done automatically while publishing the new bundle.

Guilhem

**Comment by zbw1983** [comment] 2017-09-26 08:46
OK, this time I tested on a standalone search head. 

I just restarted the splunk on that server. And seems "JFSFILE >> File System Percentage Usage" are changed to "STORAGE >> FIle Systems utilization statistics".  And in this page, I can see "/export2" partition, but I can only find the server with new nmon-logger installed, all other servers are disappeared. Seems it is not compatible with old nmon-logger version. 

And I still can't find /export2 under "NMON LIGHT ANALYSIS" page. 

Is it as expected? 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-09-26 09:59
Hi Bowen,

Right, could you please confirm the Splunk version running in your search head ?

- The STORAGE UI is not currently designed to manage both data (I will update this for 1.9.12), so yes it specific

- The Summary overview should have switched to the DF_STORAGE data when it is available on that host, within the panel title you should have had:

`File System usage statistics (external DF_STORAGE collection)
`
**And when only the JFSFILE is available, you would have:**

`File System Percent utilization (internal JFSFILE collection)
`
- Can you check the Nmon Analyser view as well ? It should switch also to the new data collection.

- For the host with the new nmon-logger version, can you please confirm that the following query returns a result:

`eventtype=nmon:performance type=DF_STORAGE host=xxxxxxx | head 100 | stats count | where count>0`

Thank you,

**Comment by zbw1983** [comment] 2017-09-26 10:37
Our splunk version is 6.5.2

And yes, I can find "external DF_STORAGE collection" under "nmon analysers" page, not sure why I didn't see it before. 

This search, it can return result "100"
eventtype=nmon:performance type=DF_STORAGE host=xxxxxxx | head 100 | stats count | where count>0

Seems I need wait for 1.9.12 version, I don't want to update all nmon-logger version at this time. Thanks for your support, when new version is ready, please let me know, I will update it on my splunk cluster. 

By the way, I found new "analysis" page has a new network chart,  and a new drop-down box named "auto-refresh", whose default value is "30 sec", then on my search head,  some charts are always in "loading data" status(a blue process bar on top of chart), this may confuse some end users and make them have a bad experience. Maybe it is caused by my test search head is too busy, I will pay attention on this change to see whether it impact the performance.  

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-09-26 10:53
Ok thanks for the feedback.

- So, does the Nmon Summary overview provides you the result for the upgraded server now ?
- I understand the Nmon Analyser view is ok with the new collection
- The STORAGE interface will be updated to manage both collections

Regards,

Guilhem

**Comment by guilhemmarchand** [comment] 2017-09-26 14:08
Related to the issue you raised with the auto-refresh, you said you were deploying the new release to a standalone search head, would you mean that is was testing purposes on a independent server from your main search heads ? (which are in clusters maybe ?)

I am asking because most probably that means that all the data model acceleration were not built for the search head, and as such not providing good performance results.

As well, the auto refresh feature is deactivated when you look at past data only (example yesterday)
In the future release, I could make it being automatically for large relative periods. (when selecting last 7 or 30 days for example)

Regards,

Guilhem

**Comment by guilhemmarchand** [comment] 2017-09-26 23:38
Hello Bowen,

I have updated the core application, version 1.9.12, and the nmon-logger, version 2.0.10.

For the nmon-logger:
- The JFSFILE has been reactivated by default (mainly to prevent the FS stats to be unavailable for users until the core application release is available on Splunk base)

For the core app:
- The STORAGE UI has a dropdown for the collection, just switch to JFSFILE and you can select the legacy collection
- The Dark dashboard switches automatically depending on the DF_STORAGE availability, which is the case for the Summary overview and the Nmon analyser view

Regards,

Guilhem

**Comment by zbw1983** [comment] 2017-09-27 01:45
Thanks a lot, I will have a test for this new version later. 

For 1.9.11, yes, I can see both new nmon-logger version server and old nmon-logger version. 

And for performance, yes, I tested it on a stand alone server, but before it also had old version NMON, so suppose the data model acceleration should be built before. I will check the performance on new version when I deploy it on our search head cluster. 

Regards
Bowen

**Comment by zbw1983** [comment] 2017-10-10 02:26
sorry for the reply delay, I am in holiday last week. 

Yesterday I upgraded 1.9.12 on my PRD environment, but I still found it is very slow. In "Nmon summary lightly analysis" page,  after about 4 minutes, there is no chart completely loaded.  
If you want to see the page, you can visit this address: 

URL: https://pan.baidu.com/s/1c13NoNu 
Password: 66z4

While before I used 1.8.6 version, about 10s, I can see the "CPU usage" and "IOPS" charts, after 30s, nearly all charts are finished. 

I am not sure what's wrong of new version on my side, seems I need degrade nmon version before we find the root cause. I am not sure whether you can reproduce this problem on your side, if you need more information, please let me know. 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-10-10 06:50
Hi Bowen,

Ok, I've checked the screenshot and yes obviously something seems to go wrong.

Are the data model acceleration activated ?

Go to: Settings / Data models

And verify that Nmon data model have acceleration activated at least for a certain period.

Regards,

Guilhem

**Comment by zbw1983** [comment] 2017-10-10 07:17
Hi Guilhem: 

I use default settings, suppose all data model accelerations are activated. I checked it on my test server, all accelerations are activated. So I suppose on our PRD ENV, they are also enabled. I  degraded nmon on PRD because it is too slow now. 

And how long I should wait for finishing those accelerations? After I upgrade nmon more that 12 hours, I still met this problem. Our search head cluster has 3 servers(16 cores) , and we have about 1000 servers in NMON now. 

I just check the status of data model accelerations on test server, I found some of them are in building status, and some are not 100% complete. I am not sure whether it impacts the performance or not, I upgraded nmon on this test server more that 8 days ago. 

By the way, I found the summary range of those data model accelerations are "All time", if I change it to  7 days, can it make those accelerations run a little fast? 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-10-10 08:37
Hi Bowen,

Actually, since version 1.9.12, all the acceleration of data models are disabled by default due to new Splunk certifications requirements.

The acceleration is being managed via Splunk Web, or by a local/datamodels.conf within your deployment.

To answer your question, yes should restrict the data model acceleration periods to a shorter window, in your test server I suggest you run over the last 7 or 30 days for testing purposes.

**Right, could you please in your testing server:**

- check if you have any local copy of data models in "/opt/splunk/etc/apps/nmon/local/data/models/"
- if you have any remove the .json files
- restart Splunk
- go in Settings / data models and configure what you want in acceleration period
- for each data model, click on "Rebuild" to completely rebuild the data model

Once the data models will be rebuilt, we should have good performances results.

Let me know how this goes.

Regards,

Guilhem

**Comment by zbw1983** [comment] 2017-10-11 09:34
Hi Guilhem:

Seem it is the root cause, acceleration is disabled by default, after I enable it, I can get the chart soon. Thanks for your great support, I have updated nmon on our PRD, till now it works well. 

Regards
Bowen

**Comment by zbw1983** [comment] 2017-10-11 09:38
By the way, I found "base line" and "predictive"  page can't work on my side. 

On "NMON Baseline Analysis" page, there is no base_line in chart
On "NMON Predictive interface", there is no data. 

Do you know what's wrong? 
![screen shot 2017-10-11 at 5 36 52 pm](https://user-images.githubusercontent.com/14027480/31433093-dcc5ee86-aeaa-11e7-8518-838e8eb31173.png)
![screen shot 2017-10-11 at 5 37 09 pm](https://user-images.githubusercontent.com/14027480/31433096-dcf6ee00-aeaa-11e7-80e7-0427fce7acbd.png)

**Comment by guilhemmarchand** [comment] 2017-10-11 10:49
Hello Bowen,

Great ! Happy to read we solved your issues regarding data model acceleration and app performances.

**Regarding the baseline and predictive interfaces:**

**baseline:**

The baseline interface requires that you have the baseline KVstores filled with the result analysis of the server historical data, this is managed by several reports:

- Generate NMON Baseline KV Collection *

These scheduled reports are by default scheduled to run once a week, during the WE.

Can you try running the "Generate NMON Baseline KV Collection for CPU_ALL" ?

At the end, this report should generate usual threshold (upper / average / lower) values on a per server basis, which will be used by the baseline interface.

This KV collection is accessible via "| inputlookup nmon_baseline_CPU_ALL" 

**predictive:**

Right, we might need some step to understand what's going on.

- does the list of servers populates properly ?
- when you select one server, do you have the list of metrics populated as well ?

regards,

Guilhem

**Comment by zbw1983** [comment] 2017-10-12 05:45
Hi Guilhem:

Thanks a lot. After I generate nmon_baseline_CPU_ALL lookup table, I can see baseline of CPU information. Seem those lookup tables default run time is 1 week later (on my server it is Oct.15), this may confuse new user, they can't use this function in first week. Maybe you can add some notice for those information on the page. 

And for predictive, seems I didn't choose metrics, after I select metrics, I can see the predictive page. 

Thanks for your great support, now seems everything work well. 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-10-13 08:00
Hello Bowen,

Thank you for your feedback, and you are welcome I am happy we solved your issues.
I will check if I can implement a dynamic message for the baseline generation and availability.

Thank you using Nmon app ;-)

Cheers,

Guilhem

Note: Can I assume that the DF_STORAGE works as expected and answeres to your needs ? If so I will close this issue.

**Comment by zbw1983** [comment] 2017-10-13 08:10
Hi Guilhem:

Thanks for your great help, yes, I think you can close this issue, new version fixed our "/export2/" partition issue. 

Another question I want to get your suggestion, about best practice of using NMON. 
We totally have about 1500 servers will be added into NMON(now we have about 1000 already in NMON), is there any suggestion of how to configure NMON or Splunk, to make NMON have better performance and less resource usage? 

We have 3 splunk search heads with 16 cores in each server, is it enough for NMON with thousand of servers?  I really appreciate if you have any suggestion or share some experience. I hope our company can fully use NMON to monitor system matrix. 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-10-13 12:08
Hi Bowen,

I will be happy to help you getting the best configuration possible.

One question, when you speak about "NMON performance and less resource usage", you are talking about the Splunk side is that right ? (I mean not the CPU / Memory overhead on the server)

**I encourage you to have a read on the following document:**

[http://nmon-for-splunk.readthedocs.io/en/latest/large_scale_deployment.html](url)

Now, talking about the future of the application, you might know already that Splunk 7 has introduced new concepts related to the metric management with the metric store indexes and the metric related new commands. (mstats / mcatalog)

These concepts are especially meaningful in the context of the Nmon application, as such I am already working on the upcoming major release of the app which fully implements metrics natively in Splunk.

**The next Nmon app generation will especially:**

- Indexes all metrics as native metrics in the metric store indexes
- Only a few data will be indexed as events (performance: UPTIME / UARG, configuration and internal)
- All data models (but the configuration data model) will be removed from the application

In term of Splunk related costs (overhead on the search head, indexers) will be much reduced and incredibly optimised, searches using mstats will perform much better than today for a much lower cost on the Splunk infrastructure.

This comes as well with an new metrics native hierarchy and many improvements.

Finally, please be aware that the Nmon application suite will be split into a "Community edition", and an "Enterprise edition", the free Community solution will have soft limitations (which are not fully defined yet) and the Enterprise edition will provide the full range of features of the Nmon Splunk suite.
This to be able to continue providing the best application ever for Splunk Linux & Unix monitoring application ;-)
The limitations and term of usage are not yet defined, but I will be happy to follow up with you.

Any way, regarding the current version of the Nmon app, the documentation should provide you the keys to understand what are the "costs" on the Splunk side, don't hesitate as well to consult the "Total Cost of Ownership" dashboard embedded within the application.

Does that replies to your questions ?

Feel free if not completely.

Kind regards,

Guilhem

**Comment by zbw1983** [comment] 2017-10-16 09:37
Hi Guilhem:

Thanks for your so detail reply. In fact, before when I setup NMON, I had read "large scale deployment" page. Seems there is some news for new version, I will have a detail look of it. 

Seems lots of changes in Splunk 7, I will schedule a upgrade in next year. 

And for "Enterprise edition", do you mean we may need pay some money for using NMON? Not a good news :), seems I need require some budget in future. And when you have more information about it, please let me know. I need evaluate how it impact our usage. Thank you. 

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-10-23 19:36
Hello Bowen,

Sorry for late reply, busy hard working on the metric store ;-)

**Since you have read the large scale documentation page, I can expand some of the key points of a large Nmon deployment:**

**measurements accuracy:**

- Users and companies sometimes choose a different level of accuracy between 2 measures (interval / snapshot options in nmon.conf) to reduce the volume of data to be generated by the servers, which means obviously saving licencing costs and eventually storage (or more data depth for the same costs)

The price to pay is the accuracy of the measurements,which might not be what you want to monitor Production systems, this might something interesting for non Production servers thought.

**Indexes design and retention:**

For a fine tuning of Nmon app and Splunk, I would definitively recommend a fine tuning of your indexes design and retention.

Again if you have multiple environments generating data into your Nmon Splunk deployment, I would recommend having a per environment index design.
This could even be split into more than 1 index for each environment, per region, per state or data center, etc.  

More indexes means that you can apply different retention settings (ex. 1 year or more for Production, 3 months for non Productions) and save storage (raw data and data model acceleration) plus performance regarding the data model acceleration creation.

Splunk is a very flexible solution as you know, so there are multiple ways to manage that depending on your deployment, this can be done when the data reach your indexers on the flight (at indexing time with custom transforms and index Meta rewrite rules), on the input level in your syslog receivers, etc.

I will be happy to help if you need any help regarding that kind of configuration.

** data model acceleration management:**

As you understood from the documentation, most of the costs on the Splunk platform are related to the data model implementation, until Splunk 7 and the metric stores this was indeed the best way to provide the highest level of performance for Nmon app.
However, the more data you have, the more rebuilding and maintaining have infrastructure costs.

You may wish to fine tune the acceleration periods on a per data model basis to manage this up to your needs.
   
**Regarding the Enterprise version:**

Yes, you understood properly ;-)

My goal is to continue improving the application suite with more performances, lowest infrastructure costs, best design and best value from your data.
As you probably appreciate, this represents a huge amount of permanent work, if we success in creating value with the application, I will have more freedom to continue working on it, and working on various other ideas I have for other powerful Splunk applications.

The details are not ready yet, however people will still have the choice to use the current events based version without any restriction, or switch to the commercial version implementing the metric store. (this is the plan)

I will be perfectly happy to follow up on this you.

Kind regards,

Guilhem

**Comment by zbw1983** [comment] 2017-11-21 09:32
Hi Guilhem:

Many thanks for your information. 

For interval settings, yes, before I use default settings (60s), now I plan to change fifo_interval to 120 seconds, hope it can save some license and improve the performance. 

For separating different environments, you mean I need use different index name. Beside using two indexes, what other work I need do? I suppose I need create two NMON apps on splunk search head, and update all data model and other settings, is there any easy way for those work? 

By the way, some users said new NMON version is slower than before. I try to get last 7 days disk space usage data, using the "UI STORAGE, utilization statistics of file systems” dashboard, after 20 minutes, I still can’t get the whole chart. Even the last 24 hours data, it needs about 3 minutes, I am not sure whether it is normal or not. 

The search command is like below: 

| tstats max("JFS.value") AS JFS.value from datamodel=NMON_Data_JFS
where (nodename = JFS.JFSFILE) (JFS.value>=0) (host=*) (JFS.frameID="*") (JFS.OStype="Linux") (host="nycelkes01.fwmrm.net") (JFS.device="*") (JFS.device="*") groupby _time, host, "JFS.device" prestats=true span=1m
| stats dedup_splitvals=t max("JFS.value") AS JFS.value by _time, host, "JFS.device"
| rename "JFS.*" AS *
| eval key=host+":"+device
| timechart `nmon_span` limit=0 useother=f latest(value) As value by key

Regards
Bowen

**Comment by guilhemmarchand** [comment] 2017-11-22 06:36
Hello Bowen,

You are welcome.

**Regarding application speed:**

First for the speed of the queries, and your example above, it should not obviously take that long and the result should be very quick.

Is the datamodel "NMON_Data_JFS." accelerated over at least the last 7 days ?
If the acceleration is activated, I would suggest you to re-build the acceleration (Settings / data models / develop the data model and click on re-build), it could be out of date and not properly accelerated.

Please let me know.

**Regarding the indexes segmentation:** 

The Nmon app is built on top of eventtypes, which means that it comes with a "default/eventtypes.conf" that drives all the searches. (including the data models constraints)

By default, any index that starts by "nmon" will be transparently managed from the search head(s) where the Nmon app is deployed.

So, if you have multiple indexes, either multiple standalone indexers or multiple cluster indexers, you can segment the indexing with custom indexes, this could be on a per environment basis, location, etc...

**Let's take an example:**

you have Production and non-Production servers, your Splunk search head(s) is/are able to search across both environments. (each env has its own indexers) 

You deploy the TA-nmon with a local configuration which is specific for each environment (a local/inputs.conf that tells the UF to index into "nmon_prod" for Production and "nmon_nonprod" for non Production)

If you are using the same Splunk deployment server for all environments, you can use a script I am providing (create_agent.py) to create different copies properly of the TA-nmon (ex: TA-nmon-prod / TA-nmon-nonprod) and deploy according to your env,
 
Finally once you've done that, you have nothing more to do since the eventtypes search for any index that start with "nmon*", and the macros as well.

If you need to have a completely naming convention, then you need to customise eventtypes.conf and macros.conf.

The deployment of the Nmon application on the search head depends of your Splunk architecture, if your Production search talks only to Production indexers which receive only data from Production servers and you have the same architecture for other env, then your deploy the Nmon app on the search head in each env.
If your search head(s) is/are able to search across all indexers, then you deploy the Nmon app only once.

I hope this helps, let me know.

Regards 

Guilhem

**Comment by guilhemmarchand** [comment] 2017-11-22 06:51
Hi Bowen,

I just realise that you are using the nmon-logger package, not the TA-nmon on a Splunk Universal Forwarder, so your data initially come from Syslog.

For the indexes management, that is the same but you only need to work on your heavy forwarders deployed on top of your syslog receivers.

For the indexes naming convention, this is the same.

**Comment by zbw1983** [comment] 2017-12-08 06:35
Hi Guilhem:

Many thanks. For speed issue, yes, I forgot to accelerate some datamodels, after I enable them, the speed is OK now. 

For indexes segmentation, thanks for your detail information. Seems all data model are based on source type, so after I separate different environment index, the performance and server load are same with one index, Separating index can save disk capacity, but no impact on performance, is it right? 

Regards
Bowen

**Closed as completed** 2019-11-06 23:03 UTC
